project:
  type: website

format: 
  revealjs:
    menu: false
    controls: false
    section-divs: true
    preview-links: false
    link-external-newwindow: true
    embed-resources: true
    transition: fade
    background-transition: fade
    navigation-mode: linear
    email-obfuscation: javascript
    theme: theme.scss
    footer: '**Paul Johnson //** Simulation-Based Hypothesis Testing **//** Jan 24, 2025'
    progress: true
    multiplex: false
    scrollable: false
    hide-inactive-cursor: true
    highlight-style: printing
    pause: true
    fig-width: 6
    fig-height: 7
    fig-align: center
    output-location: column

editor: source

knitr:
  opts_chunk: 
    dev: "ragg_png"
    retina: 1
    dpi: 300

execute:
  freeze: auto
  echo: true
  warning: false

revealjs-plugins:
  - verticator
  
bibliography: references.bib

title-slide-attributes:
    data-background-image: "man/figures/logo.jpg"
    data-background-position: "right 5% bottom 5%"
    data-background-size: "22%"
    data-background-opacity: "1"

from: markdown+emoji